const FETCH_TESTER = 'tester/FETCH_TESTER';
const FETCH_TESTER_SUCCESS = 'tester/FETCH_TESTER_SUCCESS';
const FETCH_TESTER_FAILD = 'tester/FETCH_TESTER_FAILD';

const CHANGE_SORT_BY = 'tester/CHANGE_SORT_BY';
const CHANGE_SORT_ASCENDING = 'tester/CHANGE_SORT_ASCENDING';

export default {
  FETCH_TESTER,
  FETCH_TESTER_SUCCESS,
  FETCH_TESTER_FAILD,
  CHANGE_SORT_BY,
  CHANGE_SORT_ASCENDING,
}
